const products = [
  {
    id: "price_1MecxUJna0QE1h10NuNpc3AS",
    name: "watch show",
    description: "watch freepik",
    price: 165.1,
    currency: "USD",
    image: "products/watch/watch-show.png",
  },
  {
    id: "price_1Mecx7Jna0QE1h10CyMmboEx",
    name: "pocket watch",
    description: "watch freepik",
    price: 135,
    currency: "USD",
    image: "products/watch/pocket-watch.png",
  },
  {
    id: "price_1MecwiJna0QE1h101HwDgqcy",
    name: "female watch",
    description: "watch freepik",
    price: 230,
    currency: "USD",
    image: "products/watch/female-watch.png",
  },
  {
    id: "price_1MecvhJna0QE1h10GieIAuM1",
    name: "collection of watches",
    description: "watch freepik",
    price: 160,
    currency: "USD",
    image: "products/watch/collection-of-watches.png",
  },
  {
    id: "price_1MectSJna0QE1h10taawCQmv",
    name: "Birthday Watch",
    description: "watch freepik",
    price: 110,
    currency: "USD",
    image: "products/watches/brithday-watch.png",
  },
  {
    id: "price_1MecszJna0QE1h10w6RGqZWA",
    name: "unbranded modern sporty",
    description: "sneakers freepik",
    price: 225,
    currency: "USD",
    image: "products/sneakers/unbranded-modern-sporty-shoe.png",
  },
  {
    id: "price_1MecsZJna0QE1h10YX9U8zRS",
    name: "pair of workout sneakers",
    description: "sneakers freepik",
    price: 195,
    currency: "USD",
    image: "products/sneakers/pair of workout sneakers on white background.png",
  },
  {
    id: "price_1Mecs8Jna0QE1h10URchpLaF",
    name: "fashion shoes and sneakers",
    description: "sneakers freepik",
    price: 190,
    currency: "USD",
    image: "products/sneakers/fasion-shoes-and-sneakers-(2).png",
  },
  {
    id: "price_1MecrQJna0QE1h10UcaJ1sWf",
    name: "New pair of white sneakers",
    description: "sneakers freepik",
    price: 135,
    currency: "USD",
    image: "products/sneakers/New-pair-of white-sneakers-2.png",
  },
  {
    id: "price_1MecqkJna0QE1h10UvA5O1Hj",
    name: "Female Sneakers for run",
    description: "sneakers freepik",
    price: 210,
    currency: "USD",
    image: "products/sneakers/Female-Sneakers-for-run.png",
  },
  {
    id: "price_1MecqLJna0QE1h10mZRIRcwE",
    name: "fashion sneakers",
    description: "sneakers freepik",
    price: 154,
    currency: "USD",
    image: "products/sneakers/fashion-shoes-and-sneakers.png",
  },
  {
    id: "price_1MecpXJna0QE1h10B48JsYbV",
    name: "fashion shoe",
    description: "sneakers freepik",
    price: 124,
    currency: "USD",
    image: "products/sneakers/Fashion-Shoe.png",
  },
  {
    id: "price_1MecoaJna0QE1h10mPRraOAC",
    name: "a pair of trainers",
    description: "sneakers freepik",
    price: 100,
    currency: "USD",
    image: "products/sneakers/a-pair-of-trainers.png",
  },
  {
    id: "price_1Meco7Jna0QE1h10xTXuMRZA",
    name: "Life Rendering of jacket Front",
    description: "jackets freepik",
    price: 220,
    currency: "USD",
    image: "products/sneakers/Still Life Rendering of jacket Front display.png",
  },
  {
    id: "price_1MecnRJna0QE1h10rKh80sfw",
    name: "Life Rendering of Red jacket",
    description: "jackets from freepik",
    price: 250,
    currency: "USD",
    image: "products/sneakers/Still Life Rendering of Red jacket display.png",
  },
  {
    id: "price_1MecmVJna0QE1h10VUZMZMB3",
    name: "Orange Jackets",
    description: "jackets from freepik",
    price: 180,
    currency: "USD",
    image: "products/sneakers/Orange Jacket.png",
  },
  {
    id: "price_1Mecm0Jna0QE1h10MIsRHy90",
    name: "Life Show of jacket display",
    description: "jackets from freepik",
    price: 220,
    currency: "USD",
    image: "products/sneakers/Still Life Rendering of jacket Front display 2.png",
  },
  {
    id: "price_1Mecl6Jna0QE1h10hizd6fJS",
    name: "Front View of Hoodie Jeans",
    description: "jackets from freepik",
    price: 200,
    currency: "USD",
    image: "products/sneakers/Front View of Hoodie Jeans.png",
  },
  {
    id: "price_1MeckVJna0QE1h10KOotv53u",
    name: "Greet Cap Fashion",
    description: "hats from freepik",
    price: 140,
    currency: "USD",
    image: "products/sneakers/Great Cap fasion white elegance.png",
  },
  {
    id: "price_1MecjwJna0QE1h10xrSglNGJ",
    name: "Fasion Beauty Sunwear",
    description: "hats from freepik",
    price: 180,
    currency: "USD",
    image: "products/sneakers/Fasion Beauty Sunwear.png",
  },
  {
    id: "price_1MecjIJna0QE1h10dzyMaOml",
    name: "Canvas Hat Blank Fasion Sport",
    description: "hats from freepik",
    price: 170,
    currency: "USD",
    image: "products/sneakers/Canvas Hat Blank Fasion Sport.png",
  },
  {
    id: "price_1MecioJna0QE1h10qer7fbld",
    name: "Background Hats Ladies Clothing Sun",
    description: "hats from freepik",
    price: 200,
    currency: "USD",
    image: "products/sneakers/Background Hats Ladies Clothing Sun.png",
  },
  {
    id: "price_1MeciRJna0QE1h10GOWCYXc6",
    name: "Background Hat Vintage Female",
    description: "hats from freepik",
    price: 160,
    currency: "USD",
    image: "products/sneakers/Background Hat Vintage Female.png",
  },
  {
    id: "price_1MechxJna0QE1h10igSu3rNb",
    name: "Acessory Traditional Clothing",
    description: "hats from freepik",
    price: 120,
    currency: "USD",
    image: "products/sneakers/Acessory Traditional Clothing.png",
  },
  {
    id: "price_1MecgfJna0QE1h10jFsHA8N7",
    name: "green leather hand bag",
    description: "bag from freepik",
    price: 150,
    currency: "USD",
    image: "products/sneakers/leather hand bag.png",
  },
  {
    id: "price_1Mecg9Jna0QE1h104IaC6VyZ",
    name: "Female Hand Bag",
    description: "bag from freepik",
    price: 110,
    currency: "USD",
    image: "products/sneakers/female hand bag.png",
  },
  {
    id: "price_1MecdCJna0QE1h10O1aaf2SO",
    name: "elegance yellow bag",
    description: "bag from freepik",
    price: 120,
    currency: "USD",
    image: "products/sneakers/elegance yellow bag.png",
  },
  {
    id: "price_1MecbzJna0QE1h10mhPsF8ZJ",
    name: "Capcius female purse",
    description: "bag from freepik",
    price: 75,
    currency: "USD",
    image: "products/sneakers/Capcius female purse.png",
  },
  {
    id: "price_1MeccbJna0QE1h10jta0lkXW",
    name: "cotton tote bags",
    description: "bag from freepik",
    price: 90,
    currency: "USD",
    image: "products/sneakers/cotton tote bags.png",
  },
  {
    id: "price_1MeccbJna0QE1h10jta0lkXW",
    name: "Black tote bag",
    description: "bag from freepik",
    price: 100,
    currency: "USD",
    image: "products/sneakers/Black tote bag.png",
  },
];

export default products;
